services:
  mosquitto:
    image: eclipse-mosquitto:2.0
    container_name: mosquitto
    ports:
      - "1883:1883"
    volumes:
      - ./config/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - ./config/passwordfile:/mosquitto/config/passwordfile
      - ./data:/mosquitto/data
      - ./log:/mosquitto/log
    restart: unless-stopped
